name: 'verify-jar-action'
description: 'Fail the build if any .class file in a JAR is compiled for a higher Java version than allowed'

branding:
  icon: 'search'
  color: 'white'

inputs:
  directory:
    description: 'Directory to scan for JARs'
    required: false
    default: 'target'
  bytecode-version:
    description: |
      Maximum allowed class file bytecode version (major version). For example: 52 = Java 8, 55 = Java 11, 61 = Java 17.
      Any .class file compiled for a higher version will cause the build to fail.
    required: false
    default: '52'
  max-checks:
    description: 'Maximum number of .class files to check per JAR to speed up the validation (0 = no limit, all files checked)'
    required: false
    default: '0'

runs:
  using: 'composite'
  steps:
    - name: 'Inspect and verify jars'
      id: java
      shell: bash
      env:
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_BYTECODE_VERSION: ${{ inputs.bytecode-version }}
        INPUT_MAX_CHECKS: ${{ inputs.max-checks }}
      run: ${{ github.action_path }}/verify.sh
